baseURL = "https://lightbi-beta-demo.netlify.app/"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
languageCode = "en"
title = "Lightbi"
theme = "lightbi-hugo"
summaryLength  = "30"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = true
pygmentOptions = "linenos=inline"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
ignoreLogs = ['warning-goldmark-raw-html']

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = true
wordCount = true
hideAuthor = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true 
gcse = false
Lastmod = false
rss = true 
pagination = "10"
description="Your can add your website description here."
lunrSearch = true
previewCardImagePlacement = "bottom"
hidePostImage = false

[pagination]
pagerSize = 6

[languages]
  [languages.en]
    LanguageCode  = "en"
    LanguageName = "English"
    weight = 1
    title = "Lightbi"
    contentDir = "content/en"

  [languages.ml]
    LanguageCode  = "ml"
    LanguageName = "Malayalam"
    weight = 2
    title = "Malayalam Site"
    contentDir = "content/ml"

[Params.Author]
  name = "Bino Kochumol Varghese"
  website = "https://www.binovarghese.com/"
  authorInfo = "Give everything for your dreams."
  authorPostImage = "/img/author-post-img.jpg"
  facebook = "username"
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  twitter = "username"
  linkedin = "username"
  github = "username"
  threads = "username"
  gitlab = "username"
  reddit = "username"
  stackoverflow = "users/XXXXXXX/username"
  snapchat = "username"
  spotify = "username"
  paypal = "username"
  telegram = "username"
  mastodon = "url"
  slack = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #500px = "username"
  #kaggle = "username"
  #weibo = "username"
  #xing = "username"
  #bitbucket = "username"
  #soundcloud = "username"
  # codepen = "username"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3


[[menu.main]]
    name = "Collections"
    url = "/collections/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5



