baseURL = "https://lightbi-hugo-theme.netlify.app/"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Lightbi"
theme = "lightbi-hugo"
summaryLength  = "30"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true 
gcse = false
Lastmod = false
rss = true 
pagination = "10"
hideAuthor = false
authorInfo = "She was born to be free, let her run wild in her own way and you will never lose her."
description="Your can add your website description here."
lunrSearch = true
previewCardImagePlacement = "bottom"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Bino Kochumol Varghese"
  website = "https://binovarghese.com"
  email = "sample@gmail.com"
  facebook = "username"
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  twitter = "username"
  linkedin = "username"
  github = "username"
  threads = "username"
  gitlab = "username"
  reddit = "username"
  stackoverflow = "users/XXXXXXX/username"
  snapchat = "username"
  spotify = "username"
  paypal = "username"
  telegram = "username"
  mastodon = "url"
  slack = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #500px = "username"
  #kaggle = "username"
  #weibo = "username"
  #xing = "username"
  #bitbucket = "username"
  #soundcloud = "username"
  # codepen = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3


[[menu.main]]
    name = "Collections"
    url = "/collections/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5



